// Login mit Basic Authentication als admin mit korrekten Credentials admin:123
###
# @name loginAdminCorrect
GET http://localhost:8080/authenticate
Authorization: Basic YWRtaW46MTIz

@adminToken = {{loginAdminCorrect.response.headers.Authorization}}

### Alle Foren ausgeben
GET http://localhost:8080/forumThreads

### Auflisten der Foren des aktuellen users -positivtest
GET http://localhost:8080/forumThreads/myForumThreads
Authorization: {{adminToken}}


###Forum erstellen. Sollte nur ein Authentifizierter Nutzer Dürfen
POST http://localhost:8080/forumThreads  
Authorization: {{adminToken}}
Content-Type: application/json

{
    "name": "Mein ezweites Forum",
    "description": "Das ist ein erstes Forum, das ich im Rahmen der Tests angelegt habe"
}

### Auflisten der Foren einen bestimmten user
GET http://localhost:8080/forumThreads?ownerID=manfred
