http://localhost:8080/

###
GET http://localhost:8080/publicUsers

//user erstellen -> 200
###
POST http://localhost:8080/publicUsers
Content-Type: application/json

{
    "userID" : "melanie",
    "userName": "Test",
    "password": "23424",
    "isAdministrator": false
}
//user doppelt erstellen -> 400
###
POST http://localhost:8080/publicUsers
Content-Type: application/json

{
    "userID" : "melanie",
    "userName": "Test",
    "password": "23424",
    "isAdministrator": false
}
//user ohne ID hinzufügen->400
###
POST http://localhost:8080/publicUsers
Content-Type: application/json

{
    "userName": "Test",
    "password": "23424",
    "isAdministrator": false
}

// Rufe den User mit UserID  ab. _> sollte 200
###
GET http://localhost:8080/publicUsers/melanie
// Rufe den User mit UserID  ab, der nicht exesitert sollte 400
###
GET http://localhost:8080/publicUsers/flasche

//update melanie->200
###
PUT http://localhost:8080/publicUsers/melanie
Content-Type: application/json

{
    "userName": "hans Mustermann"
}
//update user den es nicht gibt->400
###
PUT http://localhost:8080/publicUsers/flasche
Content-Type: application/json

{
    "userName": "hans Mustermann"
}
//update user, ohne id-> 400
###
PUT http://localhost:8080/publicUsers/
Content-Type: application/json

{
    "userName": "hans Mustermann"
}


//User löschen den es gibt -200
###
DELETE http://localhost:8080/publicUsers/lili
//User löschen den es gibt -400
###
DELETE http://localhost:8080/publicUsers/melanie
//User löschen ohne id-400
###
DELETE http://localhost:8080/user/lili
