http://localhost:8080/

// Login mit Basic Authentication als admin mit korrekten Credentials admin:123
###
# @name loginAdminCorrect
GET http://localhost:8080/authenticate
Authorization: Basic YWRtaW46MTIz

@adminToken = {{loginAdminCorrect.response.headers.Authorization}}

### :) Auflisten aller Nutzer mit Token von admin
http://localhost:8080/users
Authorization: {{adminToken}}

### :( Auflisten aller Nutzer mit Token von admin
http://localhost:8080/users


### :) Lege neuen user manfred an
POST http://localhost:8080/users
Authorization: {{adminToken}}
Content-Type: application/json

{
    "userID": "jana",
    "userName": "manni Mustermann",
    "password": "asdf"
}

### :( Lege neuen user manfred an
POST http://localhost:8080/users
Content-Type: application/json

{
    "userID": "jana",
    "userName": "manni Mustermann",
    "password": "asdf"
}

### :) Abrufen des angelegten Users mit dem Admin-Token
GET http://localhost:8080/users/jan
Authorization: {{adminToken}}

### :( Abrufen des angelegten Users mit dem Admin-Token
GET http://localhost:8080/users/jan

### :) User Updaten
PUT http://localhost:8080/users/jana
Authorization: {{adminToken}}
Content-Type: application/json

{
    "userName": "jana Mustermann"
}

### :( User Updaten
PUT http://localhost:8080/users/jan
Content-Type: application/json

{
    "userName": "jan Mustermann"
}

### :( Delete USer ohne token
DELETE http://localhost:8080/users/jan
Content-Type: application/json

### :) Delete USer
DELETE http://localhost:8080/users/jan
Authorization: {{adminToken}}
Content-Type: application/json